// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bfrlyelijakfnahwaqrx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJmcmx5ZWxpamFrZm5haHdhcXJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwODQxMTcsImV4cCI6MjA2MTY2MDExN30.eHP1sl9eG-2-Cq_g99VYc--YusqnwENhxz1TuSmnl8c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);